// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tahmkoikqlkoodmhhufs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhaG1rb2lrcWxrb29kbWhodWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjE4NjIsImV4cCI6MjA3MTY5Nzg2Mn0.PU6ZO1N5JFdKevFPkP2xyQuim_1Y2GJ6GbkXawC6LMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});